# Generated by Django 4.0.5 on 2022-06-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comments'),
        ('MsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSWordComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MSWordComments', to='MsApp.msword')),
            ],
            options={
                'verbose_name_plural': 'MSWordComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='MSPowerpointComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MSPowerpointComments', to='MsApp.mspowerpoint')),
            ],
            options={
                'verbose_name_plural': 'MSPowerpointComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='MSOneNoteComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MSOneNoteComments', to='MsApp.msonenote')),
            ],
            options={
                'verbose_name_plural': 'MSOneNoteComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='MSExcelComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MSExcelComments', to='MsApp.msexcel')),
            ],
            options={
                'verbose_name_plural': 'MSExcelComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
