# Generated by Django 4.0.5 on 2022-06-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MsApp', '0002_mswordcomments_mspowerpointcomments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msexcel',
            options={'verbose_name_plural': 'MSExcel'},
        ),
        migrations.AlterModelOptions(
            name='msonenote',
            options={'verbose_name_plural': 'MSOneNote'},
        ),
        migrations.AlterModelOptions(
            name='mspowerpoint',
            options={'verbose_name_plural': 'MSPowerpoint'},
        ),
        migrations.AlterModelOptions(
            name='msword',
            options={'verbose_name_plural': 'MSWord'},
        ),
    ]
