# Generated by Django 4.0.5 on 2022-07-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MsApp', '0003_alter_msexcel_options_alter_msonenote_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msonenotecomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='msonenotecomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='mspowerpointcomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='mspowerpointcomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='mswordcomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='mswordcomments',
            name='post',
        ),
        migrations.DeleteModel(
            name='MSExcelComments',
        ),
        migrations.DeleteModel(
            name='MSOneNoteComments',
        ),
        migrations.DeleteModel(
            name='MSPowerpointComments',
        ),
        migrations.DeleteModel(
            name='MSWordComments',
        ),
    ]
