# Generated by Django 4.0.5 on 2022-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MsApp', '0006_mswordlike_mspowerpointlike_msonenotelike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msexcel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MsApp.msexcelparent'),
        ),
        migrations.AlterField(
            model_name='msonenote',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MsApp.msonenoteparent'),
        ),
        migrations.AlterField(
            model_name='mspowerpoint',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MsApp.mspowerpointparent'),
        ),
        migrations.AlterField(
            model_name='msword',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MsApp.mswordparent'),
        ),
    ]
