# Generated by Django 4.0.5 on 2022-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsApp', '0007_alter_msexcel_parent_alter_msonenote_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msexcel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='msonenote',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mspowerpoint',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='msword',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
