# Generated by Django 4.0.5 on 2022-06-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_androidprojects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='androidprojects',
            options={'verbose_name_plural': 'AndroidProjects'},
        ),
        migrations.AlterModelOptions(
            name='cplusprojects',
            options={'verbose_name_plural': 'CPlusProjects'},
        ),
        migrations.AlterModelOptions(
            name='cprojects',
            options={'verbose_name_plural': 'CProjects'},
        ),
        migrations.AlterModelOptions(
            name='csharpprojects',
            options={'verbose_name_plural': 'CSharpProjects'},
        ),
        migrations.AlterModelOptions(
            name='dotnetprojects',
            options={'verbose_name_plural': 'DotNetProjects'},
        ),
        migrations.AlterModelOptions(
            name='javaprojects',
            options={'verbose_name_plural': 'JavaProjects'},
        ),
        migrations.AlterModelOptions(
            name='javascriptprojects',
            options={'verbose_name_plural': 'JavaScriptProjects'},
        ),
        migrations.AlterModelOptions(
            name='kotlinprojects',
            options={'verbose_name_plural': 'KotlinProjects'},
        ),
        migrations.AlterModelOptions(
            name='phpprojects',
            options={'verbose_name_plural': 'PHPProjects'},
        ),
        migrations.AlterModelOptions(
            name='pythonprojects',
            options={'verbose_name_plural': 'PythonProjects'},
        ),
        migrations.AlterModelOptions(
            name='rprojects',
            options={'verbose_name_plural': 'RProjects'},
        ),
        migrations.AlterModelOptions(
            name='swiftprojects',
            options={'verbose_name_plural': 'SwiftProjects'},
        ),
    ]
