# Generated by Django 4.0.5 on 2022-06-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cplusprogramme',
            options={'verbose_name_plural': 'CPlusProgramme'},
        ),
        migrations.AlterModelOptions(
            name='cprogramme',
            options={'verbose_name_plural': 'CProgramme'},
        ),
        migrations.AlterModelOptions(
            name='csharpprogramme',
            options={'verbose_name_plural': 'CSharpProgramme'},
        ),
        migrations.AlterModelOptions(
            name='dotnetprogramme',
            options={'verbose_name_plural': 'DotNetProgramme'},
        ),
        migrations.AlterModelOptions(
            name='javaprogramme',
            options={'verbose_name_plural': 'JavaProgramme'},
        ),
        migrations.AlterModelOptions(
            name='javascriptprogramme',
            options={'verbose_name_plural': 'JavaScriptProgramme'},
        ),
        migrations.AlterModelOptions(
            name='kotlinprogramme',
            options={'verbose_name_plural': 'KotlinProgramme'},
        ),
        migrations.AlterModelOptions(
            name='phpprogramme',
            options={'verbose_name_plural': 'PHPProgramme'},
        ),
        migrations.AlterModelOptions(
            name='pythonprogramme',
            options={'verbose_name_plural': 'PythonProgramme'},
        ),
        migrations.AlterModelOptions(
            name='rprogramme',
            options={'verbose_name_plural': 'RProgramme'},
        ),
        migrations.AlterModelOptions(
            name='swiftprogramme',
            options={'verbose_name_plural': 'SwiftProgramme'},
        ),
    ]
