# Generated by Django 4.0.5 on 2022-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0004_swiftprogrammelike_rprogrammelike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cplusprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.cplusprogrammeparent'),
        ),
        migrations.AlterField(
            model_name='cprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.cprogrammeparent'),
        ),
        migrations.AlterField(
            model_name='csharpprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.csharpprogrammeparent'),
        ),
        migrations.AlterField(
            model_name='dotnetprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.dotnetprogrammeparent'),
        ),
        migrations.AlterField(
            model_name='javaprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.javaprogrammeparent'),
        ),
        migrations.AlterField(
            model_name='javascriptprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.javascriptprogrammeparent'),
        ),
        migrations.AlterField(
            model_name='kotlinprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.kotlinprogrammeparent'),
        ),
        migrations.AlterField(
            model_name='phpprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.phpprogrammeparent'),
        ),
        migrations.AlterField(
            model_name='pythonprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.pythonprogrammeparent'),
        ),
        migrations.AlterField(
            model_name='rprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.rprogrammeparent'),
        ),
        migrations.AlterField(
            model_name='swiftprogramme',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.swiftprogrammeparent'),
        ),
    ]
