# Generated by Django 4.0.5 on 2022-06-26 13:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_tutlist_link'),
        ('PythonApp', '0003_restapi_restapicomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSPython',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DSPython',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DSPythonComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DSPythoncomments', to='PythonApp.dspython')),
            ],
            options={
                'verbose_name_plural': 'DSPythonComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
