# Generated by Django 4.0.5 on 2022-06-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApp', '0004_dspython_dspythoncomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datascience',
            options={'verbose_name_plural': 'DataScience'},
        ),
        migrations.AlterModelOptions(
            name='deeplearning',
            options={'verbose_name_plural': 'DeepLearning'},
        ),
        migrations.AlterModelOptions(
            name='django',
            options={'verbose_name_plural': 'Django'},
        ),
        migrations.AlterModelOptions(
            name='dspython',
            options={'verbose_name_plural': 'DSPython'},
        ),
        migrations.AlterModelOptions(
            name='flask',
            options={'verbose_name_plural': 'Flask'},
        ),
        migrations.AlterModelOptions(
            name='jupyters',
            options={'verbose_name_plural': 'Jupyters'},
        ),
        migrations.AlterModelOptions(
            name='kivys',
            options={'verbose_name_plural': 'Kivys'},
        ),
        migrations.AlterModelOptions(
            name='machinelearning',
            options={'verbose_name_plural': 'MachineLearning'},
        ),
        migrations.AlterModelOptions(
            name='matplotlibs',
            options={'verbose_name_plural': 'Matplotlibs'},
        ),
        migrations.AlterModelOptions(
            name='numpys',
            options={'verbose_name_plural': 'Numpys'},
        ),
        migrations.AlterModelOptions(
            name='opencvs',
            options={'verbose_name_plural': 'OpenCVs'},
        ),
        migrations.AlterModelOptions(
            name='pandass',
            options={'verbose_name_plural': 'Pandass'},
        ),
        migrations.AlterModelOptions(
            name='pillows',
            options={'verbose_name_plural': 'Pillows'},
        ),
        migrations.AlterModelOptions(
            name='pygames',
            options={'verbose_name_plural': 'Pygames'},
        ),
        migrations.AlterModelOptions(
            name='pytorchs',
            options={'verbose_name_plural': 'Pytorchs'},
        ),
        migrations.AlterModelOptions(
            name='restapi',
            options={'verbose_name_plural': 'RestApi'},
        ),
        migrations.AlterModelOptions(
            name='scipys',
            options={'verbose_name_plural': 'Scipys'},
        ),
        migrations.AlterModelOptions(
            name='seleniums',
            options={'verbose_name_plural': 'Seleniums'},
        ),
        migrations.AlterModelOptions(
            name='tensorflows',
            options={'verbose_name_plural': 'Tensorflows'},
        ),
        migrations.AlterModelOptions(
            name='tkinters',
            options={'verbose_name_plural': 'Tkinters'},
        ),
    ]
