# Generated by Django 4.0.5 on 2022-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApp', '0008_tkinterslike_tensorflowslike_seleniumslike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascience',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.datascienceparent'),
        ),
        migrations.AlterField(
            model_name='deeplearning',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.deeplearningparent'),
        ),
        migrations.AlterField(
            model_name='django',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.djangoparent'),
        ),
        migrations.AlterField(
            model_name='dspython',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.dspythonparent'),
        ),
        migrations.AlterField(
            model_name='flask',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.flaskparent'),
        ),
        migrations.AlterField(
            model_name='jupyters',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.jupytersparent'),
        ),
        migrations.AlterField(
            model_name='kivys',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.kivysparent'),
        ),
        migrations.AlterField(
            model_name='machinelearning',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.machinelearningparent'),
        ),
        migrations.AlterField(
            model_name='matplotlibs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.matplotlibsparent'),
        ),
        migrations.AlterField(
            model_name='numpys',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.numpysparent'),
        ),
        migrations.AlterField(
            model_name='opencvs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.opencvsparent'),
        ),
        migrations.AlterField(
            model_name='pandass',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.pandassparent'),
        ),
        migrations.AlterField(
            model_name='pillows',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.pillowsparent'),
        ),
        migrations.AlterField(
            model_name='pygames',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.pygamesparent'),
        ),
        migrations.AlterField(
            model_name='pytorchs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.pytorchsparent'),
        ),
        migrations.AlterField(
            model_name='restapi',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.restapiparent'),
        ),
        migrations.AlterField(
            model_name='scipys',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.scipysparent'),
        ),
        migrations.AlterField(
            model_name='seleniums',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.seleniumsparent'),
        ),
        migrations.AlterField(
            model_name='tensorflows',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.tensorflowsparent'),
        ),
        migrations.AlterField(
            model_name='tkinters',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonApp.tkintersparent'),
        ),
    ]
