# Generated by Django 4.0.5 on 2022-06-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a2hosting',
            options={'verbose_name_plural': 'A2Hosting'},
        ),
        migrations.AlterModelOptions(
            name='aws',
            options={'verbose_name_plural': 'AWS'},
        ),
        migrations.AlterModelOptions(
            name='bluehost',
            options={'verbose_name_plural': 'BlueHost'},
        ),
        migrations.AlterModelOptions(
            name='digitalocean',
            options={'verbose_name_plural': 'DigitalOcean'},
        ),
        migrations.AlterModelOptions(
            name='githubhost',
            options={'verbose_name_plural': 'GithubHost'},
        ),
        migrations.AlterModelOptions(
            name='godaddy',
            options={'verbose_name_plural': 'GoDaddy'},
        ),
        migrations.AlterModelOptions(
            name='greengeeks',
            options={'verbose_name_plural': 'GreenGeeks'},
        ),
        migrations.AlterModelOptions(
            name='herokuapp',
            options={'verbose_name_plural': 'HerokuApp'},
        ),
        migrations.AlterModelOptions(
            name='hostgator',
            options={'verbose_name_plural': 'HostGator'},
        ),
        migrations.AlterModelOptions(
            name='hostinger',
            options={'verbose_name_plural': 'Hostinger'},
        ),
        migrations.AlterModelOptions(
            name='inmotionhosting',
            options={'verbose_name_plural': 'InMotionHosting'},
        ),
        migrations.AlterModelOptions(
            name='msazure',
            options={'verbose_name_plural': 'MSAzure'},
        ),
        migrations.AlterModelOptions(
            name='pythonanywhere',
            options={'verbose_name_plural': 'PythonAnywhere'},
        ),
    ]
