# Generated by Django 4.0.5 on 2022-06-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comments'),
        ('DatabaseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqliteDBComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SqliteDBComments', to='DatabaseApp.sqlitedb')),
            ],
            options={
                'verbose_name_plural': 'SqliteDBComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='PostgreSQLDBComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostgreSQLDBComments', to='DatabaseApp.postgresqldb')),
            ],
            options={
                'verbose_name_plural': 'PostgreSQLDBComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='OracleDBComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OracleDBComments', to='DatabaseApp.oracledb')),
            ],
            options={
                'verbose_name_plural': 'OracleDBComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='MysqlDBComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysql', to='DatabaseApp.mysqldb')),
            ],
            options={
                'verbose_name_plural': 'MysqlDBComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='MongoDBComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MongoDBComments', to='DatabaseApp.mongodb')),
            ],
            options={
                'verbose_name_plural': 'MongoDBComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='MariaDBComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MariaDBComments', to='DatabaseApp.mariadb')),
            ],
            options={
                'verbose_name_plural': 'MariaDBComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
