# Generated by Django 4.0.5 on 2022-07-06 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApp', '0005_mariadbparent_mongodbparent_mysqldbparent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mariadb',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DatabaseApp.mariadbparent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mongodb',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DatabaseApp.mongodbparent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mysqldb',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DatabaseApp.mysqldbparent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oracledb',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DatabaseApp.oracledbparent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postgresqldb',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DatabaseApp.postgresqldbparent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sqlitedb',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DatabaseApp.sqlitedbparent'),
            preserve_default=False,
        ),
    ]
