# Generated by Django 4.0.5 on 2022-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Programming-Language', 'Programming-Language'), ('Preparation ', 'Preparation '), ('Theory-Tutorial', 'Theory-Tutorial'), ('Python', 'Python'), ('Java ', 'Java '), ('Database-Tutorial', 'Database-Tutorial'), ('Web-Technology', 'Web-Technology'), ('Microsoft-Office', 'Microsoft-Office')], default='Python', max_length=100)),
                ('image', models.ImageField(upload_to='tut-icon/')),
                ('link', models.URLField()),
            ],
        ),
    ]
