# Generated by Django 4.0.5 on 2022-06-20 07:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutCommon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='tutlist',
            options={'verbose_name_plural': 'Tut-Lists'},
        ),
        migrations.AlterField(
            model_name='tutlist',
            name='type',
            field=models.CharField(choices=[('Programming-Language', 'Programming-Language'), ('Preparation', 'Preparation'), ('Theory-Tutorial', 'Theory-Tutorial'), ('Python', 'Python'), ('Java', 'Java'), ('Javascript', 'Javascript'), ('Database-Tutorial', 'Database-Tutorial'), ('Web-Technology', 'Web-Technology'), ('Microsoft-Office', 'Microsoft-Office'), ('Versioning-Control', 'Versioning-Control')], default='Python', max_length=100),
        ),
    ]
