# Generated by Django 4.0.5 on 2022-06-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_tutlist_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutlist',
            name='type',
            field=models.CharField(choices=[('Programming-Language', 'Programming-Language'), ('Preparation', 'Preparation'), ('Theory-Tutorial', 'Theory-Tutorial'), ('Python', 'Python'), ('Java', 'Java'), ('Javascript', 'Javascript'), ('Database-Tutorial', 'Database-Tutorial'), ('Web-Technology', 'Web-Technology'), ('Microsoft-Office', 'Microsoft-Office'), ('Versioning-Control', 'Versioning-Control'), ('Web-Hosting', 'Web-Hosting')], default='Python', max_length=100),
        ),
    ]
