# Generated by Django 4.0.5 on 2022-06-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_alter_tutlist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutlist',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
