# Generated by Django 4.0.5 on 2022-07-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_alter_blogs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='ip_address',
            field=models.GenericIPAddressField(default='45.243.82.169'),
        ),
    ]
