# Generated by Django 4.0.5 on 2022-07-05 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0015_articlebookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='articlebookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
