# Generated by Django 4.0.5 on 2022-07-07 07:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_blogslike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
