# Generated by Django 4.0.5 on 2022-07-07 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0023_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='EmailVerification',
        ),
    ]
