# Generated by Django 4.0.5 on 2022-07-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0028_alter_profileimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(default='userprofile/default.jpg', upload_to='userprofile'),
        ),
    ]
