# Generated by Django 4.0.5 on 2022-07-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0034_alter_blogs_timestamp_alter_comments_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutlist',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
