# Generated by Django 4.0.5 on 2022-06-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comments'),
        ('VCApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GitsComments', to='VCApp.gits')),
            ],
            options={
                'verbose_name_plural': 'GitsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='GithubsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GithubsComments', to='VCApp.githubs')),
            ],
            options={
                'verbose_name_plural': 'GithubsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='DockerComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DockerComments', to='VCApp.docker')),
            ],
            options={
                'verbose_name_plural': 'DockerComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
