# Generated by Django 4.0.5 on 2022-07-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VCApp', '0003_alter_docker_options_alter_githubs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubscomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='githubscomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='gitscomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='gitscomments',
            name='post',
        ),
        migrations.DeleteModel(
            name='DockerComments',
        ),
        migrations.DeleteModel(
            name='GithubsComments',
        ),
        migrations.DeleteModel(
            name='GitsComments',
        ),
    ]
