# Generated by Django 4.0.5 on 2022-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VCApp', '0006_gitslike_githubslike_dockerlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VCApp.dockerparent'),
        ),
        migrations.AlterField(
            model_name='githubs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VCApp.githubsparent'),
        ),
        migrations.AlterField(
            model_name='gits',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VCApp.gitsparent'),
        ),
    ]
