# Generated by Django 4.0.5 on 2022-06-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comments'),
        ('JavaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpringFrameworkComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpringFrameworkComments', to='JavaApp.springframework')),
            ],
            options={
                'verbose_name_plural': 'SpringFrameworkComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='SpringBootComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpringBootComments', to='JavaApp.springboot')),
            ],
            options={
                'verbose_name_plural': 'SpringBootComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='ServletsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServletsComments', to='JavaApp.servlets')),
            ],
            options={
                'verbose_name_plural': 'ServletsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='JSPsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JSPsComments', to='JavaApp.jsps')),
            ],
            options={
                'verbose_name_plural': 'JSPsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='JavaSwingsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JavaSwingsComments', to='JavaApp.javaswings')),
            ],
            options={
                'verbose_name_plural': 'JavaSwingsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='JavaIOComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JavaIOComments', to='JavaApp.javaio')),
            ],
            options={
                'verbose_name_plural': 'JavaIOComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='JavaFXsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JavaFXsComments', to='JavaApp.javafxs')),
            ],
            options={
                'verbose_name_plural': 'JavaFXsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='JavaDateComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JavaDateComments', to='JavaApp.javadate')),
            ],
            options={
                'verbose_name_plural': 'JavaDateComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='JavaAWTComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JavaAWTComments', to='JavaApp.javaawt')),
            ],
            options={
                'verbose_name_plural': 'JavaAWTComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='HibernatesComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HibernatesComments', to='JavaApp.hibernates')),
            ],
            options={
                'verbose_name_plural': 'HibernatesComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='CollectionsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CollectionsComments', to='JavaApp.collections')),
            ],
            options={
                'verbose_name_plural': 'CollectionsComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
