# Generated by Django 4.0.5 on 2022-06-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JavaApp', '0002_springframeworkcomments_springbootcomments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='hibernates',
            options={'verbose_name_plural': 'Hibernates'},
        ),
        migrations.AlterModelOptions(
            name='javaawt',
            options={'verbose_name_plural': 'JavaAWT'},
        ),
        migrations.AlterModelOptions(
            name='javadate',
            options={'verbose_name_plural': 'JavaDate'},
        ),
        migrations.AlterModelOptions(
            name='javafxs',
            options={'verbose_name_plural': 'JavaFXs'},
        ),
        migrations.AlterModelOptions(
            name='javaio',
            options={'verbose_name_plural': 'JavaIO'},
        ),
        migrations.AlterModelOptions(
            name='javaswings',
            options={'verbose_name_plural': 'JavaSwings'},
        ),
        migrations.AlterModelOptions(
            name='jsps',
            options={'verbose_name_plural': 'JSPs'},
        ),
        migrations.AlterModelOptions(
            name='servlets',
            options={'verbose_name_plural': 'Servlets'},
        ),
        migrations.AlterModelOptions(
            name='springboot',
            options={'verbose_name_plural': 'SpringBoot'},
        ),
        migrations.AlterModelOptions(
            name='springframework',
            options={'verbose_name_plural': 'SpringFramework'},
        ),
    ]
