# Generated by Django 4.0.5 on 2022-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JavaApp', '0006_springframeworklike_springbootlike_servletslike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.collectionsparent'),
        ),
        migrations.AlterField(
            model_name='hibernates',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.hibernatesparent'),
        ),
        migrations.AlterField(
            model_name='javaawt',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.javaawtparent'),
        ),
        migrations.AlterField(
            model_name='javadate',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.javadateparent'),
        ),
        migrations.AlterField(
            model_name='javafxs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.javafxsparent'),
        ),
        migrations.AlterField(
            model_name='javaio',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.javaioparent'),
        ),
        migrations.AlterField(
            model_name='javaswings',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.javaswingsparent'),
        ),
        migrations.AlterField(
            model_name='jsps',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.jspsparent'),
        ),
        migrations.AlterField(
            model_name='servlets',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.servletsparent'),
        ),
        migrations.AlterField(
            model_name='springboot',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.springbootparent'),
        ),
        migrations.AlterField(
            model_name='springframework',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaApp.springframeworkparent'),
        ),
    ]
