# Generated by Django 4.0.5 on 2022-06-20 11:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtificialIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ArtificialIntelligence',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Automata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Automata',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompilerDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'CompilerDesign',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComputerGraphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ComputerGraphics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComputerNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ComputerNetwork',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComputerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ComputerOrganization',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CyberSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'CyberSecurity',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DAA',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataMining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DataMining',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DataStructure',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DBMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DBMS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DiscreteMathematics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DiscreteMathematics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'OperatingSystem',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareEngineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'SoftwareEngineering',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'WebApi',
                'ordering': ['-timestamp'],
            },
        ),
    ]
