# Generated by Django 4.0.5 on 2022-06-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comments'),
        ('TheoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebApiComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WebApiComments', to='TheoryApp.webapi')),
            ],
            options={
                'verbose_name_plural': 'WebApiComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='SoftwareEngineeringComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SoftwareEngineeringComments', to='TheoryApp.softwareengineering')),
            ],
            options={
                'verbose_name_plural': 'SoftwareEngineeringComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='OperatingSystemComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OperatingSystemComments', to='TheoryApp.operatingsystem')),
            ],
            options={
                'verbose_name_plural': 'OperatingSystemComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='DiscreteMathematicsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiscreteMathematicsComments', to='TheoryApp.discretemathematics')),
            ],
            options={
                'verbose_name_plural': 'DiscreteMathematicsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='DBMSComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DBMSComments', to='TheoryApp.dbms')),
            ],
            options={
                'verbose_name_plural': 'DBMSComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='DataStructureComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DataStructureComments', to='TheoryApp.datastructure')),
            ],
            options={
                'verbose_name_plural': 'DataStructureComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='DataMiningComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DataMiningComments', to='TheoryApp.datamining')),
            ],
            options={
                'verbose_name_plural': 'DataMiningComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='DAAComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DAAComments', to='TheoryApp.daa')),
            ],
            options={
                'verbose_name_plural': 'DAAComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='CyberSecurityComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CyberSecurityComments', to='TheoryApp.cybersecurity')),
            ],
            options={
                'verbose_name_plural': 'CyberSecurityComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='ComputerOrganizationComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComputerOrganizationComments', to='TheoryApp.computerorganization')),
            ],
            options={
                'verbose_name_plural': 'ComputerOrganizationComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='ComputerNetworkComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComputerNetworkComments', to='TheoryApp.computernetwork')),
            ],
            options={
                'verbose_name_plural': 'ComputerNetworkComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='ComputerGraphicsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComputerGraphicsComments', to='TheoryApp.computergraphics')),
            ],
            options={
                'verbose_name_plural': 'ComputerGraphicsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='CompilerDesignComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompilerDesignComments', to='TheoryApp.compilerdesign')),
            ],
            options={
                'verbose_name_plural': 'CompilerDesignComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='AutomataComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AutomataComments', to='TheoryApp.automata')),
            ],
            options={
                'verbose_name_plural': 'AutomataComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='ArtificialIntelligenceComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArtificialIntelligenceComments', to='TheoryApp.artificialintelligence')),
            ],
            options={
                'verbose_name_plural': 'ArtificialIntelligenceComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
