# Generated by Django 4.0.5 on 2022-06-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheoryApp', '0003_ddbms_ddbmscomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artificialintelligence',
            options={'verbose_name_plural': 'ArtificialIntelligence'},
        ),
        migrations.AlterModelOptions(
            name='automata',
            options={'verbose_name_plural': 'Automata'},
        ),
        migrations.AlterModelOptions(
            name='compilerdesign',
            options={'verbose_name_plural': 'CompilerDesign'},
        ),
        migrations.AlterModelOptions(
            name='computergraphics',
            options={'verbose_name_plural': 'ComputerGraphics'},
        ),
        migrations.AlterModelOptions(
            name='computernetwork',
            options={'verbose_name_plural': 'ComputerNetwork'},
        ),
        migrations.AlterModelOptions(
            name='computerorganization',
            options={'verbose_name_plural': 'ComputerOrganization'},
        ),
        migrations.AlterModelOptions(
            name='cybersecurity',
            options={'verbose_name_plural': 'CyberSecurity'},
        ),
        migrations.AlterModelOptions(
            name='daa',
            options={'verbose_name_plural': 'DAA'},
        ),
        migrations.AlterModelOptions(
            name='datamining',
            options={'verbose_name_plural': 'DataMining'},
        ),
        migrations.AlterModelOptions(
            name='datastructure',
            options={'verbose_name_plural': 'DataStructure'},
        ),
        migrations.AlterModelOptions(
            name='dbms',
            options={'verbose_name_plural': 'DBMS'},
        ),
        migrations.AlterModelOptions(
            name='ddbms',
            options={'verbose_name_plural': 'DDBMS'},
        ),
        migrations.AlterModelOptions(
            name='discretemathematics',
            options={'verbose_name_plural': 'DiscreteMathematics'},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'verbose_name_plural': 'OperatingSystem'},
        ),
        migrations.AlterModelOptions(
            name='softwareengineering',
            options={'verbose_name_plural': 'SoftwareEngineering'},
        ),
        migrations.AlterModelOptions(
            name='webapi',
            options={'verbose_name_plural': 'WebApi'},
        ),
    ]
