# Generated by Django 4.0.5 on 2022-06-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cplusquestionanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.cplusexercise'),
        ),
        migrations.AlterField(
            model_name='cquestionanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.cexercise'),
        ),
        migrations.AlterField(
            model_name='csharpquestionanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.csharpexercise'),
        ),
        migrations.AlterField(
            model_name='dotnetquestionanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.dotnetexercise'),
        ),
        migrations.AlterField(
            model_name='javaquestionanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.javaexercise'),
        ),
        migrations.AlterField(
            model_name='kotlinquestionanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.kotlinexercise'),
        ),
        migrations.AlterField(
            model_name='phpquestionanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.phpexercise'),
        ),
        migrations.AlterField(
            model_name='pythonquestionanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.pythonexercise'),
        ),
        migrations.AlterField(
            model_name='rquestionanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.rexercise'),
        ),
        migrations.AlterField(
            model_name='swiftquestionanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.swiftexercise'),
        ),
    ]
