# Generated by Django 4.0.5 on 2022-06-23 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0002_alter_cplusquestionanswer_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswercommon',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionanswercommon',
            name='question',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='JavaScriptQuestionAnswer',
            fields=[
                ('questionanswercommon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exercise.questionanswercommon')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exercise.javascriptexercise')),
            ],
            bases=('Exercise.questionanswercommon',),
        ),
    ]
