# Generated by Django 4.0.5 on 2022-06-23 07:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0003_alter_questionanswercommon_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswercommon',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='questionanswercommon',
            name='question',
            field=tinymce.models.HTMLField(),
        ),
    ]
