# Generated by Django 4.0.5 on 2022-07-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0008_cexerciseparent_cplusexerciseparent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cexercise',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Exercise.cexerciseparent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cplusexercise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.cplusexerciseparent'),
        ),
        migrations.AlterField(
            model_name='csharpexercise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.csharpexerciseparent'),
        ),
        migrations.AlterField(
            model_name='dotnetexercise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.dotnetexerciseparent'),
        ),
        migrations.AlterField(
            model_name='javaexercise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.javaexerciseparent'),
        ),
        migrations.AlterField(
            model_name='javascriptexercise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.javascriptexerciseparent'),
        ),
        migrations.AlterField(
            model_name='kotlinexercise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.kotlinexerciseparent'),
        ),
        migrations.AlterField(
            model_name='phpexercise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.phpexerciseparent'),
        ),
        migrations.AlterField(
            model_name='pythonexercise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.pythonexerciseparent'),
        ),
        migrations.AlterField(
            model_name='rexercise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.rexerciseparent'),
        ),
        migrations.AlterField(
            model_name='swiftexercise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.swiftexerciseparent'),
        ),
    ]
