# Generated by Django 4.0.5 on 2022-06-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comments'),
        ('ProgrammingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiftLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SwiftLanguageComments', to='ProgrammingApp.swiftlanguage')),
            ],
            options={
                'verbose_name_plural': 'SwiftLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='RLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RLanguageComments', to='ProgrammingApp.rlanguage')),
            ],
            options={
                'verbose_name_plural': 'RLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='PythonLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PythonLanguageComments', to='ProgrammingApp.pythonlanguage')),
            ],
            options={
                'verbose_name_plural': 'PythonLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='PHPLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PHPLanguageComments', to='ProgrammingApp.phplanguage')),
            ],
            options={
                'verbose_name_plural': 'PHPLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='KotlinLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KotlinLanguageComments', to='ProgrammingApp.kotlinlanguage')),
            ],
            options={
                'verbose_name_plural': 'KotlinLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='JavaLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JavaLanguageComments', to='ProgrammingApp.javalanguage')),
            ],
            options={
                'verbose_name_plural': 'JavaLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='CsharpLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CsharpLanguageComments', to='ProgrammingApp.csharplanguage')),
            ],
            options={
                'verbose_name_plural': 'CsharpLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='CplusLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CplusLanguageComments', to='ProgrammingApp.cpluslanguage')),
            ],
            options={
                'verbose_name_plural': 'CplusLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='CLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CLanguageComments', to='ProgrammingApp.clanguage')),
            ],
            options={
                'verbose_name_plural': 'CLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='AndroidLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AndroidLanguageComments', to='ProgrammingApp.androidlanguage')),
            ],
            options={
                'verbose_name_plural': 'AndroidLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
