# Generated by Django 4.0.5 on 2022-06-22 06:48

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comments'),
        ('ProgrammingApp', '0002_swiftlanguagecomments_rlanguagecomments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotNetLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DotNetLanguage',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JavaScriptLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('viewcounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'JavaScriptLanguag',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JavaScriptLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JavaScriptLanguageComments', to='ProgrammingApp.javalanguage')),
            ],
            options={
                'verbose_name_plural': 'JavaScriptLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='DotNetLanguageComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DotNetLanguageComments', to='ProgrammingApp.dotnetlanguage')),
            ],
            options={
                'verbose_name_plural': 'DotNetLanguageComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
