# Generated by Django 4.0.5 on 2022-06-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingApp', '0003_dotnetlanguage_javascriptlanguage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='javascriptlanguage',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'JavaScriptLanguage'},
        ),
        migrations.AlterField(
            model_name='javascriptlanguagecomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JavaScriptLanguageComments', to='ProgrammingApp.javascriptlanguage'),
        ),
    ]
