# Generated by Django 4.0.5 on 2022-06-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingApp', '0004_alter_javascriptlanguage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='androidlanguage',
            options={'verbose_name_plural': 'AndroidLanguage'},
        ),
        migrations.AlterModelOptions(
            name='clanguage',
            options={'verbose_name_plural': 'CLanguage'},
        ),
        migrations.AlterModelOptions(
            name='cpluslanguage',
            options={'verbose_name_plural': 'CplusLanguage'},
        ),
        migrations.AlterModelOptions(
            name='csharplanguage',
            options={'verbose_name_plural': 'CsharpLanguage'},
        ),
        migrations.AlterModelOptions(
            name='dotnetlanguage',
            options={'verbose_name_plural': 'DotNetLanguage'},
        ),
        migrations.AlterModelOptions(
            name='javalanguage',
            options={'verbose_name_plural': 'JavaLanguage'},
        ),
        migrations.AlterModelOptions(
            name='javascriptlanguage',
            options={'verbose_name_plural': 'JavaScriptLanguage'},
        ),
        migrations.AlterModelOptions(
            name='kotlinlanguage',
            options={'verbose_name_plural': 'KotlinLanguage'},
        ),
        migrations.AlterModelOptions(
            name='phplanguage',
            options={'verbose_name_plural': 'PHPLanguage'},
        ),
        migrations.AlterModelOptions(
            name='pythonlanguage',
            options={'verbose_name_plural': 'PythonLanguage'},
        ),
        migrations.AlterModelOptions(
            name='rlanguage',
            options={'verbose_name_plural': 'RLanguage'},
        ),
        migrations.AlterModelOptions(
            name='swiftlanguage',
            options={'verbose_name_plural': 'SwiftLanguage'},
        ),
    ]
