# Generated by Django 4.0.5 on 2022-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingApp', '0008_swiftlanguagelike_rlanguagelike_pythonlanguagelike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidlanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.androidlanguageparent'),
        ),
        migrations.AlterField(
            model_name='clanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.clanguageparent'),
        ),
        migrations.AlterField(
            model_name='cpluslanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.cpluslanguageparent'),
        ),
        migrations.AlterField(
            model_name='csharplanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.csharplanguageparent'),
        ),
        migrations.AlterField(
            model_name='dotnetlanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.dotnetlanguageparent'),
        ),
        migrations.AlterField(
            model_name='javalanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.javalanguageparent'),
        ),
        migrations.AlterField(
            model_name='javascriptlanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.javascriptlanguageparent'),
        ),
        migrations.AlterField(
            model_name='kotlinlanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.kotlinlanguageparent'),
        ),
        migrations.AlterField(
            model_name='phplanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.phplanguageparent'),
        ),
        migrations.AlterField(
            model_name='pythonlanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.pythonlanguageparent'),
        ),
        migrations.AlterField(
            model_name='rlanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.rlanguageparent'),
        ),
        migrations.AlterField(
            model_name='swiftlanguage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingApp.swiftlanguageparent'),
        ),
    ]
