# Generated by Django 4.0.5 on 2022-06-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comments'),
        ('PreparationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbalAbilityComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VerbalAbilityComments', to='PreparationApp.verbalability')),
            ],
            options={
                'verbose_name_plural': 'VerbalAbilityComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='ReasoningComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReasoningComments', to='PreparationApp.reasoning')),
            ],
            options={
                'verbose_name_plural': 'ReasoningComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='InterviewQuestionComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InterviewQuestionComments', to='PreparationApp.interviewquestion')),
            ],
            options={
                'verbose_name_plural': 'InterviewQuestionComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='CompanyQuestionComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyQuestionComments', to='PreparationApp.companyquestion')),
            ],
            options={
                'verbose_name_plural': 'CompanyQuestionComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='AptitudeComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AptitudeComments', to='PreparationApp.aptitude')),
            ],
            options={
                'verbose_name_plural': 'AptitudeComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
