# Generated by Django 4.0.5 on 2022-07-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreparationApp', '0003_alter_aptitude_options_alter_companyquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyquestioncomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='companyquestioncomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='interviewquestioncomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='interviewquestioncomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reasoningcomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='reasoningcomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='verbalabilitycomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='verbalabilitycomments',
            name='post',
        ),
        migrations.DeleteModel(
            name='AptitudeComments',
        ),
        migrations.DeleteModel(
            name='CompanyQuestionComments',
        ),
        migrations.DeleteModel(
            name='InterviewQuestionComments',
        ),
        migrations.DeleteModel(
            name='ReasoningComments',
        ),
        migrations.DeleteModel(
            name='VerbalAbilityComments',
        ),
    ]
