# Generated by Django 4.0.5 on 2022-07-04 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0014_tutcommonparent_blogcomments_ip_address_blogs_author'),
        ('PreparationApp', '0004_remove_companyquestioncomments_comments_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'Aptitude Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.CreateModel(
            name='CompanyQuestionParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'CompanyQuestion Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.CreateModel(
            name='InterviewQuestionParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'InterviewQuestion Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.CreateModel(
            name='ReasoningParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'Reasoning Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.CreateModel(
            name='VerbalAbilityParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'VerbalAbility Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.AddField(
            model_name='aptitude',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyquestion',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reasoning',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verbalability',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aptitude',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PreparationApp.aptitudeparent'),
        ),
        migrations.AddField(
            model_name='companyquestion',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PreparationApp.companyquestionparent'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PreparationApp.interviewquestionparent'),
        ),
        migrations.AddField(
            model_name='reasoning',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PreparationApp.reasoningparent'),
        ),
        migrations.AddField(
            model_name='verbalability',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PreparationApp.verbalabilityparent'),
        ),
    ]
