# Generated by Django 4.0.5 on 2022-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreparationApp', '0006_verbalabilitylike_reasoninglike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitude',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreparationApp.aptitudeparent'),
        ),
        migrations.AlterField(
            model_name='companyquestion',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreparationApp.companyquestionparent'),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreparationApp.interviewquestionparent'),
        ),
        migrations.AlterField(
            model_name='reasoning',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreparationApp.reasoningparent'),
        ),
        migrations.AlterField(
            model_name='verbalability',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreparationApp.verbalabilityparent'),
        ),
    ]
