# Generated by Django 4.0.5 on 2022-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreparationApp', '0007_alter_aptitude_parent_alter_companyquestion_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitude',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companyquestion',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reasoning',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='verbalability',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
