# Generated by Django 4.0.5 on 2022-06-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comments'),
        ('JavaScriptApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VUEjsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VUEjsComments', to='JavaScriptApp.vuejs')),
            ],
            options={
                'verbose_name_plural': 'VUEjsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='TypeScriptsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TypeScriptsComments', to='JavaScriptApp.typescripts')),
            ],
            options={
                'verbose_name_plural': 'TypeScriptsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='ReactjsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReactjsComments', to='JavaScriptApp.reactjs')),
            ],
            options={
                'verbose_name_plural': 'ReactjsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='NodejsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NodejsComments', to='JavaScriptApp.nodejs')),
            ],
            options={
                'verbose_name_plural': 'NodejsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='JqueryComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JqueryComments', to='JavaScriptApp.jquery')),
            ],
            options={
                'verbose_name_plural': 'JqueryComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='ExpressjsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExpressjsComments', to='JavaScriptApp.expressjs')),
            ],
            options={
                'verbose_name_plural': 'ExpressjsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='AngularjsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AngularjsComments', to='JavaScriptApp.angularjs')),
            ],
            options={
                'verbose_name_plural': 'AngularjsComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
