# Generated by Django 4.0.5 on 2022-06-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JavaScriptApp', '0002_vuejscomments_typescriptscomments_reactjscomments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='angularjs',
            options={'verbose_name_plural': 'Angularjs'},
        ),
        migrations.AlterModelOptions(
            name='expressjs',
            options={'verbose_name_plural': 'Expressjs'},
        ),
        migrations.AlterModelOptions(
            name='jquery',
            options={'verbose_name_plural': 'Jquery'},
        ),
        migrations.AlterModelOptions(
            name='nodejs',
            options={'verbose_name_plural': 'Nodejs'},
        ),
        migrations.AlterModelOptions(
            name='reactjs',
            options={'verbose_name_plural': 'Reactjs'},
        ),
        migrations.AlterModelOptions(
            name='typescripts',
            options={'verbose_name_plural': 'TypeScripts'},
        ),
        migrations.AlterModelOptions(
            name='vuejs',
            options={'verbose_name_plural': 'VUEjs'},
        ),
    ]
