# Generated by Django 4.0.5 on 2022-07-04 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0014_tutcommonparent_blogcomments_ip_address_blogs_author'),
        ('JavaScriptApp', '0004_remove_expressjscomments_comments_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngularjsParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'Angularjs Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.CreateModel(
            name='ExpressjsParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'Expressjs Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.CreateModel(
            name='JqueryParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'Jquery Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.CreateModel(
            name='NodejsParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'Nodejs Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.CreateModel(
            name='ReactjsParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'Reactjs Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.CreateModel(
            name='TypeScriptsParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'TypeScripts Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.CreateModel(
            name='VUEjsParent',
            fields=[
                ('tutcommonparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.tutcommonparent')),
            ],
            options={
                'verbose_name_plural': 'VUEjs Parent',
            },
            bases=('MainApp.tutcommonparent',),
        ),
        migrations.AddField(
            model_name='angularjs',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expressjs',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jquery',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nodejs',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reactjs',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typescripts',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vuejs',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='angularjs',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.angularjsparent'),
        ),
        migrations.AddField(
            model_name='expressjs',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.expressjsparent'),
        ),
        migrations.AddField(
            model_name='jquery',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.jqueryparent'),
        ),
        migrations.AddField(
            model_name='nodejs',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.nodejsparent'),
        ),
        migrations.AddField(
            model_name='reactjs',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.reactjsparent'),
        ),
        migrations.AddField(
            model_name='typescripts',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.typescriptsparent'),
        ),
        migrations.AddField(
            model_name='vuejs',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.vuejsparent'),
        ),
    ]
