# Generated by Django 4.0.5 on 2022-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JavaScriptApp', '0006_vuejslike_typescriptslike_reactjslike_nodejslike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angularjs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.angularjsparent'),
        ),
        migrations.AlterField(
            model_name='expressjs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.expressjsparent'),
        ),
        migrations.AlterField(
            model_name='jquery',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.jqueryparent'),
        ),
        migrations.AlterField(
            model_name='nodejs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.nodejsparent'),
        ),
        migrations.AlterField(
            model_name='reactjs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.reactjsparent'),
        ),
        migrations.AlterField(
            model_name='typescripts',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.typescriptsparent'),
        ),
        migrations.AlterField(
            model_name='vuejs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JavaScriptApp.vuejsparent'),
        ),
    ]
