# Generated by Django 4.0.5 on 2022-06-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comments'),
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordpressComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WordpressComments', to='WebApp.wordpress')),
            ],
            options={
                'verbose_name_plural': 'WordpressComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='LaravelsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LaravelsComments', to='WebApp.laravels')),
            ],
            options={
                'verbose_name_plural': 'LaravelsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='JSONsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JSONsComments', to='WebApp.jsons')),
            ],
            options={
                'verbose_name_plural': 'JSONsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='HTMLsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HTMLsComments', to='WebApp.htmls')),
            ],
            options={
                'verbose_name_plural': 'HTMLsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='DotNetComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DotNetComments', to='WebApp.dotnet')),
            ],
            options={
                'verbose_name_plural': 'DotNetComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='CSSsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CSSsComments', to='WebApp.csss')),
            ],
            options={
                'verbose_name_plural': 'CSSsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='BootstrapsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BootstrapsComments', to='WebApp.bootstraps')),
            ],
            options={
                'verbose_name_plural': 'BootstrapsComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='AjaxsComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AjaxsComments', to='WebApp.ajaxs')),
            ],
            options={
                'verbose_name_plural': 'AjaxsComments',
            },
            bases=('MainApp.comments',),
        ),
    ]
