# Generated by Django 4.0.5 on 2022-06-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_wordpresscomments_laravelscomments_jsonscomments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotnetcomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='dotnetcomments',
            name='post',
        ),
        migrations.DeleteModel(
            name='DotNet',
        ),
        migrations.DeleteModel(
            name='DotNetComments',
        ),
    ]
