# Generated by Django 4.0.5 on 2022-06-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_dotnetcomments_comments_ptr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajaxs',
            options={'verbose_name_plural': 'Ajaxs'},
        ),
        migrations.AlterModelOptions(
            name='bootstraps',
            options={'verbose_name_plural': 'Bootstraps'},
        ),
        migrations.AlterModelOptions(
            name='csss',
            options={'verbose_name_plural': 'CSSs'},
        ),
        migrations.AlterModelOptions(
            name='htmls',
            options={'verbose_name_plural': 'HTMLs'},
        ),
        migrations.AlterModelOptions(
            name='jsons',
            options={'verbose_name_plural': 'JSONs'},
        ),
        migrations.AlterModelOptions(
            name='laravels',
            options={'verbose_name_plural': 'Laravels'},
        ),
        migrations.AlterModelOptions(
            name='wordpress',
            options={'verbose_name_plural': 'Wordpress'},
        ),
    ]
