# Generated by Django 4.0.5 on 2022-07-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_ajaxs_options_alter_bootstraps_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootstrapscomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='bootstrapscomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='cssscomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='cssscomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='htmlscomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='htmlscomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='jsonscomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='jsonscomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='laravelscomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='laravelscomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='wordpresscomments',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='wordpresscomments',
            name='post',
        ),
        migrations.DeleteModel(
            name='AjaxsComments',
        ),
        migrations.DeleteModel(
            name='BootstrapsComments',
        ),
        migrations.DeleteModel(
            name='CSSsComments',
        ),
        migrations.DeleteModel(
            name='HTMLsComments',
        ),
        migrations.DeleteModel(
            name='JSONsComments',
        ),
        migrations.DeleteModel(
            name='LaravelsComments',
        ),
        migrations.DeleteModel(
            name='WordpressComments',
        ),
    ]
