# Generated by Django 4.0.5 on 2022-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_wordpresslike_laravelslike_jsonslike_htmlslike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajaxs',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.ajaxsparent'),
        ),
        migrations.AlterField(
            model_name='bootstraps',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.bootstrapsparent'),
        ),
        migrations.AlterField(
            model_name='csss',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.csssparent'),
        ),
        migrations.AlterField(
            model_name='htmls',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.htmlsparent'),
        ),
        migrations.AlterField(
            model_name='jsons',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.jsonsparent'),
        ),
        migrations.AlterField(
            model_name='laravels',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.laravelsparent'),
        ),
        migrations.AlterField(
            model_name='wordpress',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.wordpressparent'),
        ),
    ]
